### ISSUE TITLE
Question about html

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [trgkanki/word_autocomplete#10]
Hi,
I was reading the new code and was wondering something about this line from `wordset.py` : 

`field = re.sub(r'<.*?>', '', field)`

Does this mean that it removes everything between < and > ? Because if it does it will also remove all mathematical formulation that contain comparison, as well as all cards containing the right combination of arrows `=>` for example.

Also, I happen to often type information in html comments when researching cards and when I don't ever need to read the text (for example, the text content of a diagram I photographed into a card). I guess this would be removed too.

I don't really care for the html comment and understand it's very specific but I was wondering if it was really useful.

Thanks!

**Comment by phu54321** [comment]
1) => gets translated to `=&gt;`, so that's not an issue
2) about math formula, maybe I could remove `[latex]~~~[/latex]` prior to that.
