### ISSUE TITLE
request : display rank number just before suggested words

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [trgkanki/word_autocomplete#11]
# Feature request

## Problem description
If I want to autocomplete with the 6th suggestion, I find that counting the words to be sure it's the 6th and not the 5th or 7th takes often longer than adding more letters, so I end up typing more of the word when I could have just autocompleted earlier. I think it defeats the purpose. It especially happens with very long words and very short ones, and I fear it will become even more of a problem once you implement n-gram completion #7 .

## Suggested solution
Display a small digit before the suggestion or just after like `apolon / apologize / (3) apoplexia / (4) apoptosis / (5) apowordsomething`
Ideally with a softer color, beige or something.
And I think it could skip the first and second number as counting those is instantaneous.

I'm using this addon a lot, thanks!

**Comment by phu54321** [comment]
Fixed in latest release.
Github hook somehow seems to be malfunctioning...
