### ISSUE TITLE
numpad issue, window 10

### ISSUE THREAD

**Issue by Laern2Do** [trgkanki/word_autocomplete#2]
hi there,

my numpad does not work with this add-on (i have double checked the numlock key). the numpad is part of my laptop keyboard and is not bluetooth or separated.

On my laptop, ctrl + the top numbers row will work for populating the suggested word but will not work with my numpad.

Also it conflicted it with the quick navigation field add-on that also use ctrl +(i). Is it possible to add an option to configure the hotkeys in the configure menu?

That would be awesome!

Thank you

**Comment by phu54321** [comment]
Splitting to two isues. This issue will only handle the numpad compatibility issue

**Comment by phu54321** [comment]
[dist.zip](https://github.com/trgkanki/word_autocomplete/files/4498411/dist.zip)

Try with this version please?

**Comment by phu54321** [comment]
Fixed w/ https://github.com/trgkanki/word_autocomplete/issues/3
