### ISSUE TITLE
Hotkey customization

### ISSUE THREAD

**Issue by phu54321** [trgkanki/word_autocomplete#3]
Issue split from https://github.com/trgkanki/word_autocomplete/issues/2

> Also it conflicted it with the quick navigation field add-on that also use ctrl +(i). Is it possible to add an option to configure the hotkeys in the configure menu? That would be awesome! Thank you

Need a way of configuring hotkeys

**Comment by phu54321** [comment]
[jquery.hotkeys](https://github.com/jeresig/jquery.hotkeys) have some nice api for hotkey customization. maybe we can use that?

**Comment by thiswillbeyourgithub** [comment]
In the meantime, users can edit `addons21/734297936/editor_field_navigation.py` and change the `ctrl` for `alt`.

That's my current workaround

**Comment by phu54321** [comment]
ETA 05/31
