### ISSUE TITLE
Ignoring non-word

### ISSUE THREAD

**Issue by phu54321** [trgkanki/word_autocomplete#5]
# Feature request

## Problem description

This addon suggests me some non-word

![image](https://user-images.githubusercontent.com/775265/82119746-f39c3280-97bb-11ea-892b-551cabef992c.png)

## Suggested solution

- 1. Ignore excessivly long word (maybe longer than 20 characters?)
- 2. Ignore non-text elements, like image paths or so. For example, project [kian](https://github.com/phu54321/kian/) adds each note's original markdown as base64 format, like this. Base64 part should not be used.

```html
    <script class="tui-md-b64" type="text/markdown"  hash="694873658">SW1tdW5lIGNoZWNrLXBvaW50IGluaGliaXRvcuyZgCDsl7DqtIDrkJwgQUIvTGlnYW5kOiB7e2MxOjpDVExBLTQsIFBELTEsIFBELUwxfX0=</script>
    <link rel="stylesheet" type="text/css" href="_kian_katex.min.css">
    <link rel="stylesheet" type="text/css" href="_kian_github_markdown.css">
    <div class="markdown-body tui-html"><p>Immune check-point inhibitor와 연관된 AB/Ligand: {{c1::CTLA-4, PD-1, PD-L1}}</p></div>
```

## Alternative solutions you've thought of

Maybe we can infer what is word and what is not, but that seems a bit dangerous option. We aren't doing machine learning so

**Comment by thiswillbeyourgithub** [comment]
I think you just have to change the line 
`alphaNumeric = re.compile("[a-zA-Z][a-zA-Z0-9]{4,}")`
with
`alphaNumeric = re.compile("[a-zA-Z][a-zA-Z0-9]{4,20}")`
in the init file

**Comment by phu54321** [comment]
Basic fix initiated. Hope this works :)

**Comment by thiswillbeyourgithub** [comment]
I don't think it did. I ended up adding the 20 caracter limit manually.

**Comment by phu54321** [comment]
@thiswillbeyourgithub I'm rather reluctant to add 20-character enforcements, cause the criteria *may* have some false positives. This addon aids on typing long words, so maybe this addon can help when typing some 25~30 character words (I haven't seen them in my notes yet). So I'm trying to exclude all possible non-word pattern in advance of excluding all n-character overflows. (of course n should be configurable via addon settings)

Could you give me an example of some non-word text that may disguise as a word? Current setting tries to exclude these things
 - All attributes of HTML are excluded (image file, audio files, ...)
 - HTML Comments excluded
 - ID of Image Occlusion Enhanced is excluded

 HTML of fields preferred.

**Comment by thiswillbeyourgithub** [comment]
Hi,
I agree with you.

I found one example of string that is not interpreted the right way from a card :

```
<div><font color="#ff0000"><b>inhibition phosphodiestérases4+5</b></font></div><font color="#ff0000"><b>→ relaxation muscle lisse bronchique</b></font><i><sub><font color="#5500ff">(moins rapide + moins puissant que&nbsp;β2-agonistes)</font></sub></i><div><br></div><div><font color="#005500">anti-inflammation</font></div><div><font color="#005500">psychostimulant</font></div><div><font color="#005500">inotrope +</font><i><sub>(coeur)</sub></i></div>
```

your addon thinks "inflammationpsychostimulant" is a word for example. Maybe you did an error in ignoring html and forgot to consider that <div> splits a word ?

another example (same thing really) : 

```
Survient <b>après plsrs jours/ contact renouvelé</b><div><b><u><font color="#ff0000">Imprévisible</font></u></b></div><div>Manifestations le + souvent:</div><div><b><font color="#0055ff">cutanéo-muqueuses</font></b></div><div><b><font color="#0055ff">bronchiques</font></b></div><div><b><font color="#0055ff">hépatiques</font></b></div><div><b><font color="#0055ff">vasculaires</font></b></div><div><b><font color="#0055ff">rénales</font></b></div><div><b><font color="#0055ff">hémato&nbsp;</font></b></div><div><b><font color="#0055ff">AEG</font></b></div>
```

**Comment by phu54321** [comment]
Solved in latest release. Github hook is broken :(
