### ISSUE TITLE
n-gram completion

### ISSUE THREAD

**Issue by phu54321** [trgkanki/word_autocomplete#7]
# Feature request

## Problem description

I've once implemented them in the past, but the code is lost :)

Basically it autocompletes `if-g-r-a` to `interferon-gamma release assay`. Character `-` specifies either space between words or the hyphen itself.

## Suggested solution

**This might be very computationally expensive to implement!** Need a better algorithm!

## Additional context

It's possible. I've done this before.

**Comment by thiswillbeyourgithub** [comment]
I think there is already a way to speed up the current process. And it would also help the implementation of this feature.

Basically : every time we type a letter the algorithm goes through all possible endings but there is no smart sorting. By that I mean that when I type "gan" I will always see "ganglion" first I think, whereas I only use the autocomplete function when I have a long word like "ganglionnary".

Where I'm getting at is that I think that your addon should remember every autocompleted word and add it to a list. If the word has never been completed before then add it on top. If the word has been completed before then move it up to the top (as it's alrealdy in the list). And when looking for a word : if the letters begin like a word that's already been completed then show it first.

This way, words that are frequently used will be suggested instantly before/during the database wide search has occured. I could also be used to show words that are almost beginning like the first letters : 
say you type "gnaglio" it could see in the list that it already completed "ganglionnary" and the distance between "ganglio" and "gnaglio" is only one letter shift.



edit : but actually I'm not sure when the wordlist is created in your code so maybe I was wrong and your code is already efficient.

**Comment by phu54321** [comment]
Seems like you're suggesting a kind of caching. Maybe I could look into it, but maybe as a separate feature request :) Since my code doesnt support displaying partial results, early results wont be shown right away. But I think it could aid in usabilities.

----

There are some optimization I've tried before, but aren't in the code.

- sublist search: when we have autocomplete list of `ga`, we only need to search inside them when querying `gang`. This sped up the process considerably.
- with such optimization, I put all the n-grams to wordSet altogether like a single word. Pretty over-expensive, but that really worked without any performance issue. Ngram are always lower prioritized than 1grams due to how scoring works.

I'm actually quite flodded with my own works right now. Implementation won't arrive soon.

**Comment by thiswillbeyourgithub** [comment]
Isn't you idea of sublist search the same thing as what I suggested?

**Comment by phu54321** [comment]
> Isn't your idea of sublist search the same thing as what I suggested?

Uh not exactly. Sublist search doesnt remember what word you've frequently used.

**Comment by thiswillbeyourgithub** [comment]
Right. You understood my suggestion. But I'm not sure I understood yours then. But hey it's your repo, if you don't have the time I understand :)

Another suggestion : a list of deck or tags that will not be used for autocomplete. It would be useful for those who have a 10k deck of a second language they're desperatly trying to learn but don't ever write cards in.

**Comment by phu54321** [comment]
Maybe I should remove stale bot :(

**Comment by phu54321** [comment]
Yeah I've implemented this before.

https://github.com/phu54321/kian/blob/develop/backend/api/autocomplete.py

Will import this code

**Comment by phu54321** [comment]
bump

**Comment by thiswillbeyourgithub** [comment]
It seems that finding bi gram in the collection would be pretty easy : https://stackoverflow.com/questions/13423919/computing-n-grams-using-python

I think it would be a super time saver for me if I could use bi or trigram completion in anki.

I know python but not really JS. Could you give me some directions as to how I should implement this ?

I am willing to do a PR but that would save me a ton of time if you could tell me directly what part of your code is relevant :)

Have a nice day.


edit: wow I didn't notice that you changed the code so much and implemented partial word matching. I'll play around with this instead of implementing bi gram for now. Thanks :)
