### ISSUE TITLE
Deck whitelist / blacklist, same with tags

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [trgkanki/word_autocomplete#8]
# Feature request

## Problem description

As mentionned in #7 , it would be great if I we could remove the suggestion from other languages. I often type medical stuff in french but have then somewhere in english in another deck, hence I have sympathetic suggested before sympathique nervous system. It's a very recurrent issue as english medical terms are often shorter than french ones.

I also fear my 2nd languages deck will increase the computation time even though I never type cards in those languages.

## Suggested solution

Implement whitelisting and blacklisting of either tags or decks. Blacklist = don't look for cards that correspond to the criteria Whitelist = only look for cards that fit the criteria.

They are not supposed to be used at the same time but I'm sure some people would find very useful to restrict the completion to only a certain deck.

Thanks!

**Comment by phu54321** [comment]
Bump

**Comment by phu54321** [comment]
whitelist has been implemented but has not yet been pushed to ankiweb. Today is addon update day (sunday), so I'm trying to fix many things today. Pending
